#!/usr/bin/env node

// @ts-check

// Exit when any build folder is missing.
if (require('./scripts/needsBuild').needsBuild()) {
  console.clear()
  console.error('Run `yarn build` before starting the production server.')
  console.log()
  process.exit(1)
}

require('./scripts/startProductionServer').startProductionServer()
